import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';

import Footer from '@/components/shared/Footer';
import Header from '@/components/shared/Header';
import { poppins } from '@/constants/fonts';

import '@/styles/globals.scss';

export const metadata: Metadata = {
    title: 'Lucky Way',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

interface IRootLayout {
    children: ReactNode;
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
};

export default RootLayout;
