import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';

import '@/styles/globals.scss';

export const metadata: Metadata = {
    title: 'Lucky Way',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

interface IRootLayout {
    children: ReactNode;
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
