import { FC, ReactNode } from 'react';
import { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import { poppins } from '@/constants/fonts';

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import '@/styles/globals.scss';

export const metadata: Metadata = {
    title: 'Lucky Way',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

export interface IRootLayout {
    children: ReactNode;
}

const RootLayout: FC<IRootLayout> = async ({ children }) => {
    const locale = await getLocale();

    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body className={poppins.className}>
                <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
            </body>
        </html>
    );
};

export default RootLayout;
